### ISSUE TITLE
Problem z testami w zadaniu 3

### ISSUE THREAD

**Issue by maciekx7** [korona-science/homework-maciekx7#2]
W zadaniu trzecim sczytuję liczbę przypadków w dniu x i w dniu x-1 (pomińmy na razie problem z tym, że można przekręcić licznik daty). Jeśli liczba przypadków różni się, to zwiększamy licznik. Sposób ten zwraca taki sam wynik dla 11 lutego, ale dla 3 marca już inny (75 zamiast 57). Nie widzę powodu, czemu testy nie przechodzą. Chyba że źle zrozumiałem polecenie i liczę co innego.

Pomożesz i powiesz, co jest nie tak?
@RouNNdeL

**Comment by RouNNdeL** [comment]
W zadaniu 3 jest błąd w treści, było to wspomniane na slacku i fb kilka razy

**Comment by maciekx7** [comment]
No tak i zrobiłem zgodnie z tym poleceniem, liczę regiony, w których dnia obecnego względem poprzedniego nie pojawiło się więcej przypadków.

**Comment by RouNNdeL** [comment]
![image](https://user-images.githubusercontent.com/22538735/76877859-49b03080-6874-11ea-91ea-86fa5d726f9d.png)

**Comment by maciekx7** [comment]
Sprawdzamy, ile jest krajow/regionów z nowymi przypadkami danego dnia.

Co robię?
1. Pobieram datę z dzisiaj, obliczam datę wczorajszą
2. Tworzę pętlę, w której iteruję po każdym Regionie/kraju i zapisuje ile jest przypadków dla regionu dnia x i dnia poprzedniego. Jeśli różnica między tymi wartościami NIE jest 0, zwiększam licznik.
3. Zwracam licznik.

Tak rozumiem nowe polecenie. Jeśli źle, to wskaż proszę, co źle rozumiem.

**Comment by RouNNdeL** [comment]
Polecenie rozumiesz dobrze, ale zadanie powinno zostać wykonane za pomocą funkcji z Pandasa, bez pętli. Najwyraźniej ta implementacja zawiera błąd
